.TH "src Directory Reference" 3 "Tue Feb 12 2013" "Carambola Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBconsumer\fP"
.br
.ti -1c
.RI "directory \fBrelay\fP"
.br
.ti -1c
.RI "directory \fBshared\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.in -1c
