.TH "src/shared Directory Reference" 3 "Tue Feb 12 2013" "Carambola Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shared Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbuffer\&.h\fP"
.br
.RI "\fIDefinition for the shared buffer used by the consumer and relay\&. \fP"
.in -1c
